server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productDB
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: product service
